# In the root of your api-rest project: docker-compose.yml

services:

  db:
    image: postgres:15-alpine
    container_name: sisreserva-db
    restart: always
    environment:
      - POSTGRES_DB=sisreserva
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sisreserva-api
    restart: on-failure

    depends_on:
      - db

    ports:
      - "8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sisreserva?currentSchema=dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8080
      - API_SECURITY_TOKEN_SECRET=123456
      - API_SECURITY_ACCESS_SECRET=123456
      - API_SECURITY_REFRESH_SECRET=123456
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=andredev.invasao@gmail.com
      - SPRING_MAIL_PASSWORD=ceuxqdpkkaygfmzl
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true


volumes:
  postgres_data: