services:

  db:
    image: postgres:15-alpine
    container_name: sisreserva-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sisreserva-api
    restart: on-failure

    depends_on:
      - db

    ports:
      - "${SERVER_PORT:?ERROR: SERVER_PORT não definida no arquivo .env}:${SERVER_PORT}"

    env_file:
      - .env.docker

    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:? SPRING_DATASOURCE_USERNAME não definida no arquivo .env}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:? SPRING_DATASOURCE_PASSWORD não definida no arquivo .env}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:? CORS_ALLOWED_ORIGINS não definida no arquivo .env}
      - API_SECURITY_TOKEN_SECRET=${API_SECURITY_TOKEN_SECRET:? API_SECURITY_TOKEN_SECRET não definida no arquivo .env}
      - API_SECURITY_ACCESS_SECRET=${API_SECURITY_ACCESS_SECRET:? API_SECURITY_ACCESS_SECRET não definida no arquivo .env}
      - API_SECURITY_REFRESH_SECRET=${API_SECURITY_REFRESH_SECRET:? API_SECURITY_REFRESH_SECRET não definida no arquivo .env}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST:? SPRING_MAIL_HOST não definida no arquivo .env}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT:? SPRING_MAIL_PORT não definida no arquivo .env}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:? SPRING_MAIL_USERNAME não definida no arquivo .env}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:? SPRING_MAIL_PASSWORD não definida no arquivo .env}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:? SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH não definida no arquivo .env}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:? SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE não definida no arquivo .env}

volumes:
  postgres_data: